services:
  - type: web
    name: abstract-trade
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: TURSO_DATABASE_URL
        value: libsql://abstract-trade-db-tian3014868710-hub.aws-ap-northeast-1.turso.io
      - key: TURSO_AUTH_TOKEN
        value: eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NzgyNDgwMzAsImlkIjoiMDE5ZGY1OTQtYjkwMS03MzNjLTk3MzQtMmZhYTU5ODY4Njc5IiwicmlkIjoiZDhmNjBjM2ItNTRlNS00NjRhLWFiYTctODcyZTE1M2FhNGY5In0.9vYEPbzYqH4PRzGLWrL_3TIvxStCO2c13DWamMypJyweKGKA3dvy7t6_Df_hJqEnfegbgJgRfzf_tDsEzKJ7Aw
